services:
    apnet_ftb.webtest.client:
        class: Apnet\FunctionalTestBundle\Framework\Client
        arguments: [ @kernel, %test.client.parameters%, @test.client.history, @test.client.cookiejar ]
        scope: prototype
